package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"example.com/pz11-graphql/graph/model"
	"example.com/pz11-graphql/internal/task"
)

func toGraphQLTask(t task.Task) *model.Task {
	return &model.Task{
		ID:          t.ID,
		Title:       t.Title,
		Description: t.Description,
		Done:        t.Done,
	}
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	t, err := r.TaskService.CreateTask(ctx, input.Title, input.Description)
	if err != nil {
		return nil, err
	}
	return toGraphQLTask(t), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	t, err := r.TaskService.UpdateTask(ctx, id, input.Title, input.Description, input.Done)
	if err != nil {
		if errors.Is(err, task.ErrTaskNotFound) {
			return nil, err
		}
		return nil, err
	}
	return toGraphQLTask(t), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	if err := r.TaskService.DeleteTask(ctx, id); err != nil {
		if errors.Is(err, task.ErrTaskNotFound) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	tasks, err := r.TaskService.ListTasks(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Task, 0, len(tasks))
	for _, t := range tasks {
		result = append(result, toGraphQLTask(t))
	}
	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	t, err := r.TaskService.GetTaskByID(ctx, id)
	if err != nil {
		if errors.Is(err, task.ErrTaskNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return toGraphQLTask(t), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
